#!/bin/sh

#
# Copyright (C) 2015  Ivan Zoratti
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

#
# @stopvm - This program shuts down a given VM sending the shutdown signal.
#            It is installed in the ~/VBox_host_extensions directory
#            of the administrator in the VirtualBox host machine
#
# @verbatim
# Revision History
#
# Date          Who             Description
# 2015-01-01    Ivan Zoratti    First Version
#
# @endverbatim
#

#set -x

stop_this_vm=`vboxmanage list vms | grep "${1}" | sort | head -1`
stop_this_vm=${stop_this_vm#*\{}
stop_this_vm=${stop_this_vm%\}*}
VBoxManage controlvm ${stop_this_vm} acpipowerbutton

exit 0
